export const projects = [
  {
    title: 'Telluride',
    description: "Using JavaScript, HTML Canvas, and CSS, this is a throwback to the Microsoft Classic Ski Free.  Original sprites imported and hit those blue ramps for style points!",
      image: '/images/telluride.png',
      tags: ['JavaScript', 'HTML', 'Canvas', 'CSS'],
    source: 'https://github.com/harrdev/Telluride-Master',
    visit: 'https://telluride.harrdev.com',
    id: 0,
  },
  {
    title: 'Skywalker Academy',
    description:"Using JavaScript, Node.js, Express, React, and MongoDB, jump into the Star Wars universe and learn about the people and planets that are a part of it.  SWAPI API used, incorporating RESTful design with full CRUD",
    image: '/images/skywalker.png',
    tags: ['JavaScript', 'Node', 'Express', 'React', 'MongoDB'],
    source: 'https://github.com/harrdev/Skywalker-Academy',
    visit: 'https://adoring-roentgen-859357.netlify.app/',
    id: 1,
  },
  {
    title: 'CryptoBytes',
    description: "Using React, JavaScript, Node.js, and MongoDB, let's go to the moon together. Track the top 100 Crypto Coins on the market. Coincap API used, ReactCharts, and incorporating RESTful design with full CRUD.",
      image: '/images/crypto.png',
      tags: ['React', 'JavaScript', 'MongoDB', 'Node'],
    source: 'https://github.com/harrdev/client-cryptoBytes',
    visit: 'https://cryptobyte.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Vinyasa Builder',
    description: "This is a Yoga Routine building app incorporating a custom seeded database using React, JavaScript, Node.js, and MongoDB.  Utilizing npm package React Beautiful DND (drag and drop), a user can reorganize their routine with just the drag of the mouse.  RESTful designed.",
    image: '/images/vinyasa.png',
    tags: ['React', 'JavaScript', 'Node.js', 'MongoDB'],
    source: 'https://github.com/harrdev/ClientVinyasa',
    visit: 'https://vinyasabuilder.herokuapp.com/',
    id: 3,
  },
];